# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "0 8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/openwrt/video"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: ""
        github_token: ${{ secrets.GITHUB_TOKEN }}
